//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpatialMapsWpfUi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF8A2BE2")]
        public global::System.Windows.Media.Color LeftPolygonColor {
            get {
                return ((global::System.Windows.Media.Color)(this["LeftPolygonColor"]));
            }
            set {
                this["LeftPolygonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7CFC00")]
        public global::System.Windows.Media.Color RightPolygonColor {
            get {
                return ((global::System.Windows.Media.Color)(this["RightPolygonColor"]));
            }
            set {
                this["RightPolygonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left Figure Area")]
        public string LeftAreaName {
            get {
                return ((string)(this["LeftAreaName"]));
            }
            set {
                this["LeftAreaName"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Made by Piotr Falkowski © 2016")]
        public string AboutString {
            get {
                return ((string)(this["AboutString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right Figure Area")]
        public string RightAreaName {
            get {
                return ((string)(this["RightAreaName"]));
            }
            set {
                this["RightAreaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left Figure Perimeter")]
        public string LeftPerimeterName {
            get {
                return ((string)(this["LeftPerimeterName"]));
            }
            set {
                this["LeftPerimeterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right Figure Perimeter")]
        public string RightPerimeterName {
            get {
                return ((string)(this["RightPerimeterName"]));
            }
            set {
                this["RightPerimeterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Area Difference")]
        public string AreaDifferenceName {
            get {
                return ((string)(this["AreaDifferenceName"]));
            }
            set {
                this["AreaDifferenceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Perimeter Difference")]
        public string PerimeterDifferenceName {
            get {
                return ((string)(this["PerimeterDifferenceName"]));
            }
            set {
                this["PerimeterDifferenceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left Overlapping Area")]
        public string LeftOverlappingAreaName {
            get {
                return ((string)(this["LeftOverlappingAreaName"]));
            }
            set {
                this["LeftOverlappingAreaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right Overlapping Area")]
        public string RightOverlappingAreaName {
            get {
                return ((string)(this["RightOverlappingAreaName"]));
            }
            set {
                this["RightOverlappingAreaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left Non-Overlapping Area")]
        public string LeftNonOverlappingAreaName {
            get {
                return ((string)(this["LeftNonOverlappingAreaName"]));
            }
            set {
                this["LeftNonOverlappingAreaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right Non-Overlapping Area")]
        public string RightNonOverlappingAreaName {
            get {
                return ((string)(this["RightNonOverlappingAreaName"]));
            }
            set {
                this["RightNonOverlappingAreaName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Overlapping Areas Sum")]
        public string OverlappingAreasSumName {
            get {
                return ((string)(this["OverlappingAreasSumName"]));
            }
            set {
                this["OverlappingAreasSumName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Non-Overlapping Areas Sum")]
        public string NonOverlappingAreasSumName {
            get {
                return ((string)(this["NonOverlappingAreasSumName"]));
            }
            set {
                this["NonOverlappingAreasSumName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Common Area %")]
        public string ResemblenceIndexName {
            get {
                return ((string)(this["ResemblenceIndexName"]));
            }
            set {
                this["ResemblenceIndexName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int ScaleFactor {
            get {
                return ((int)(this["ScaleFactor"]));
            }
            set {
                this["ScaleFactor"] = value;
            }
        }
    }
}
